'use client';
import { useMemo, useState } from 'react';
import { Bot, BarChart3, Users, EyeOff, ShieldCheck, Database, Zap, FileText, RefreshCcw, Search, Sparkles, Lock, TrendingUp, DollarSign, Radio } from 'lucide-react';

type Creator={id:string;name:string;masked:string;niche:string;followers:number;fee:number;score:number;status:string;tier:string;roas:number;revenue:number;spend:number};
type Client={id:string;name:string;brand:string;roas:number;spend:number;revenue:number;active:number};
const creators:Creator[]=[
{id:'cr_101',name:'Maya Torres',masked:'Creator #A17',niche:'Fitness / Recovery',followers:420000,fee:3200,score:92,status:'Approved',tier:'Scale',roas:4.8,revenue:78000,spend:16250},
{id:'cr_102',name:'Jordan Mills',masked:'Creator #B44',niche:'CPG / Lifestyle',followers:735000,fee:5500,score:88,status:'Live Ads',tier:'Test',roas:3.7,revenue:45200,spend:12200},
{id:'cr_103',name:'Ava Chen',masked:'Creator #C09',niche:'Mom / Wellness',followers:190000,fee:1800,score:79,status:'Brief Sent',tier:'Vet',roas:2.9,revenue:18600,spend:6400},
{id:'cr_104',name:'Kai Brooks',masked:'Creator #D81',niche:'Gym / Nutrition',followers:980000,fee:8700,score:95,status:'Winner',tier:'Scale',roas:6.2,revenue:124000,spend:20000},
{id:'cr_105',name:'Sofia Reed',masked:'Creator #E22',niche:'Beauty / CPG',followers:315000,fee:2600,score:71,status:'Needs Review',tier:'Vet',roas:1.8,revenue:9900,spend:5500}
];
const clients:Client[]=[{id:'cl_1',name:'Founder Foods',brand:'Protein Snack Brand',roas:4.9,spend:54000,revenue:265000,active:14},{id:'cl_2',name:'GlowLab',brand:'Skincare CPG',roas:3.6,spend:37000,revenue:133200,active:9},{id:'cl_3',name:'HydroFuel',brand:'Hydration Mix',roas:5.7,spend:62000,revenue:353400,active:21}];
function fmt(n:number){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n)}
function Sidebar({view,setView}:{view:string;setView:(v:string)=>void}){const items=[['ops','Operations',Users],['client','Masked Client Portal',EyeOff],['data','Data Pipeline',Database],['ai','AI Assistant',Bot],['settings','Access Control',ShieldCheck]] as const;return <aside className="w-72 min-h-screen glass p-5 fixed left-0 top-0"><div className="flex items-center gap-3 mb-8"><div className="w-11 h-11 rounded-2xl bg-lime-300 text-black font-black grid place-items-center">W2</div><div><div className="font-black text-xl">Wired2Scale</div><div className="text-xs muted">Partnership Ads OS</div></div></div><nav className="space-y-2">{items.map(([k,label,Icon])=><button key={k} onClick={()=>setView(k)} className={`navitem w-full text-left ${view===k?'active':''}`}><Icon size={18}/>{label}</button>)}</nav><div className="mt-8 p-4 rounded-2xl bg-black/30 border border-white/10"><div className="text-xs muted mb-1">Demo Mode</div><div className="font-bold">Mock APIs + AI workflows</div><p className="text-sm muted mt-2">Shows creator masking, client-safe views, ad-data sync, and AI brief generation.</p></div></aside>}
function KPI({label,value,icon:Icon}:{label:string;value:string;icon:any}){return <div className="glass rounded-3xl p-5"><Icon className="text-lime-300 mb-5"/><div className="text-3xl font-black">{value}</div><div className="muted text-sm mt-1">{label}</div></div>}
function Ops(){return <div><div className="flex justify-between items-start mb-6"><div><div className="pill inline-flex px-3 py-1 rounded-full font-bold mb-3">Internal system of record</div><h1 className="text-5xl font-black">Creator operations dashboard</h1><p className="muted mt-3 max-w-3xl">Recruit, score, approve and scale creators while tracking the performance data that powers client reporting.</p></div><button className="btn flex gap-2"><RefreshCcw size={18}/> Sync feeds</button></div><div className="grid grid-cols-4 gap-4 mb-6"><KPI label="Active creators" value="58" icon={Users}/><KPI label="Blended ROAS" value="4.7x" icon={TrendingUp}/><KPI label="Revenue tracked" value="$751k" icon={DollarSign}/><KPI label="AI briefs generated" value="126" icon={Sparkles}/></div><div className="glass rounded-3xl p-5"><div className="flex justify-between mb-4"><h2 className="text-2xl font-black">Creator pipeline</h2><div className="relative"><Search size={16} className="absolute left-3 top-3 muted"/><input className="pl-9" placeholder="Search creators"/></div></div><table><thead><tr><th>Creator</th><th>Niche</th><th>Followers</th><th>Fee</th><th>AI Score</th><th>Status</th><th>ROAS</th></tr></thead><tbody>{creators.map(c=><tr key={c.id}><td><b>{c.name}</b><div className="muted text-xs">{c.id}</div></td><td>{c.niche}</td><td>{(c.followers/1000).toFixed(0)}k</td><td>{fmt(c.fee)}</td><td>{c.score}/100</td><td><span className={`badge ${c.score>85?'good':c.score>75?'warn':'bad'}`}>{c.status}</span></td><td><b>{c.roas}x</b></td></tr>)}</tbody></table></div></div>}
function ClientPortal(){return <div><div className="mb-6"><div className="pill inline-flex px-3 py-1 rounded-full font-bold mb-3">Masked client view</div><h1 className="text-5xl font-black">Client portal without leaking creator identity</h1><p className="muted mt-3 max-w-3xl">Clients see performance, creative tier, spend and ROAS — but creator names, contacts and fees stay hidden.</p></div><div className="grid grid-cols-3 gap-4 mb-6">{clients.map(c=><div className="glass rounded-3xl p-5" key={c.id}><div className="muted text-sm">{c.brand}</div><div className="text-2xl font-black mt-1">{c.name}</div><div className="grid grid-cols-3 mt-5 gap-3 text-sm"><div><b>{c.roas}x</b><div className="muted">ROAS</div></div><div><b>{fmt(c.spend)}</b><div className="muted">Spend</div></div><div><b>{c.active}</b><div className="muted">Creators</div></div></div></div>)}</div><div className="glass rounded-3xl p-5"><h2 className="text-2xl font-black mb-4">Founder Foods performance</h2><table><thead><tr><th>Creator</th><th>Tier</th><th>Spend</th><th>Revenue</th><th>ROAS</th><th>Visibility</th></tr></thead><tbody>{creators.slice(0,4).map(c=><tr key={c.id}><td><b>{c.masked}</b><div className="muted text-xs">Identity hidden</div></td><td>{c.tier}</td><td>{fmt(c.spend)}</td><td>{fmt(c.revenue)}</td><td><b>{c.roas}x</b></td><td><span className="badge good">Masked</span></td></tr>)}</tbody></table></div></div>}
function DataPipeline(){return <div><h1 className="text-5xl font-black mb-3">Automated data feeds</h1><p className="muted max-w-3xl mb-6">Mock pipeline showing daily syncs from Meta, Northbeam and creator records into one clean system of record.</p><div className="grid grid-cols-3 gap-4">{['Meta Marketing API','Northbeam Revenue Feed','Airtable / Postgres Records'].map((x,i)=><div className="glass rounded-3xl p-6" key={x}><Radio className="text-lime-300 mb-5"/><div className="text-xl font-black">{x}</div><div className="muted mt-2">Last sync: {i+1}h ago</div><div className="h-2 bg-white/10 rounded-full mt-5"><div className="h-2 bg-lime-300 rounded-full" style={{width:`${90-i*12}%`}} /></div></div>)}</div><div className="glass rounded-3xl p-5 mt-6"><h2 className="text-2xl font-black mb-4">Recent webhook / sync events</h2>{['meta.ads.updated','northbeam.revenue.imported','creator.score.recalculated','client.portal.refreshed'].map(e=><div className="flex justify-between py-3 border-b border-white/10" key={e}><span>{e}</span><span className="badge good">Processed</span></div>)}</div></div>}
function AI(){const [prompt,setPrompt]=useState('Generate 5 ad angles for a hydration CPG brand targeting marathon runners.');const output=useMemo(()=>['Hook: Stop losing performance to poor recovery hydration.','Angle: Show a creator comparing post-run fatigue before vs after routine.','Script: 15-second founder-style UGC with product used immediately after training.','Brief: Focus on taste, fast recovery, and habit stacking after every run.','Score: Strong fit for fitness creators with 100k–500k engaged followers.'],[prompt]);return <div><h1 className="text-5xl font-black mb-3">AI creative ops assistant</h1><p className="muted max-w-3xl mb-6">Speed up briefs, scripts, ad angles, creator research and scoring. In production this would connect to OpenAI/Anthropic with brand-safe prompts.</p><div className="grid grid-cols-2 gap-5"><div className="glass rounded-3xl p-5"><label className="font-bold">Prompt</label><textarea rows={8} value={prompt} onChange={e=>setPrompt(e.target.value)} className="w-full mt-3"/><button className="btn mt-4 flex gap-2"><Bot size={18}/> Generate</button></div><div className="glass rounded-3xl p-5"><h2 className="text-2xl font-black mb-4">Generated output</h2><div className="space-y-3">{output.map(x=><div className="p-4 rounded-2xl bg-black/30 border border-white/10" key={x}>{x}</div>)}</div></div></div></div>}
function Settings(){return <div><h1 className="text-5xl font-black mb-3">Access control & masking rules</h1><p className="muted max-w-3xl mb-6">Role-aware data permissions keep internal economics protected while still giving clients useful reporting.</p><div className="grid grid-cols-2 gap-5"><div className="glass rounded-3xl p-5"><h2 className="text-2xl font-black mb-4">Client-hidden fields</h2>{['Creator legal name','Creator contact details','Creator fee','Internal margin','Negotiation notes'].map(x=><div key={x} className="flex gap-3 items-center py-3 border-b border-white/10"><Lock size={17} className="text-lime-300"/>{x}</div>)}</div><div className="glass rounded-3xl p-5"><h2 className="text-2xl font-black mb-4">Client-visible fields</h2>{['Masked creator ID','Spend','Revenue','ROAS','Creative tier','Status'].map(x=><div key={x} className="flex gap-3 items-center py-3 border-b border-white/10"><ShieldCheck size={17} className="text-lime-300"/>{x}</div>)}</div></div></div>}
export default function Home(){const[view,setView]=useState('ops');return <main className="gridbg min-h-screen"><Sidebar view={view} setView={setView}/><section className="ml-72 p-8 max-w-[1500px]">{view==='ops'&&<Ops/>}{view==='client'&&<ClientPortal/>}{view==='data'&&<DataPipeline/>}{view==='ai'&&<AI/>}{view==='settings'&&<Settings/>}</section></main>}
